package IU;

import Componentes.Mensajes;
import Componentes.Timbrado;
import Componentes.generarCodigos;
import Componentes.validarCampos;
import Controladores.ControlCaja;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

public class dlgArreglo extends javax.swing.JDialog {

    /**
     * Creates new form dlgArreglo
     *
     * @param parent
     * @param modal
     */
    public dlgArreglo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtIDCaj.setText(dlgRegistroValores.txtCaja.getText());
        txtIDBoca.setText(String.valueOf(Timbrado.getIdBoca()));
        cboConcepto.requestFocus();
        cboConceptoActionPerformed(null);
        Invisible();
    }
    
    private void Invisible(){
        txtIDCaj.setVisible(false);
        txtIDBoca.setVisible(false);
        txtIDArreglo.setVisible(false);
        txtEvento.setVisible(false);
    }

    private void Habilitar(Boolean b) {
        txt50.setEnabled(b);
        txt100.setEnabled(b);
        txt500.setEnabled(b);
        txt1000.setEnabled(b);
        txt2000.setEnabled(b);
        txt5000.setEnabled(b);
        txt10000.setEnabled(b);
        txt20000.setEnabled(b);
        txt50000.setEnabled(b);
        txt100000.setEnabled(b);
    }

    public static final void Calculadora() {
        int cincuenta = Integer.parseInt(txt50.getText().replace(".", "").replace(",", "")) * 50;
        int cien = Integer.parseInt(txt100.getText().replace(".", "").replace(",", "")) * 100;
        int quinientos = Integer.parseInt(txt500.getText().replace(".", "").replace(",", "")) * 500;
        int mil = Integer.parseInt(txt1000.getText().replace(".", "").replace(",", "")) * 1000;
        int dos_mil = Integer.parseInt(txt2000.getText().replace(".", "").replace(",", "")) * 2000;
        int cinco_mil = Integer.parseInt(txt5000.getText().replace(".", "").replace(",", "")) * 5000;
        int diez_mil = Integer.parseInt(txt10000.getText().replace(".", "").replace(",", "")) * 10000;
        int veinte_mil = Integer.parseInt(txt20000.getText().replace(".", "").replace(",", "")) * 20000;
        int cincuenta_mil = Integer.parseInt(txt50000.getText().replace(".", "").replace(",", "")) * 50000;
        int cien_mil = Integer.parseInt(txt100000.getText().replace(".", "").replace(",", "")) * 100000;

        int total = (cincuenta + cien + quinientos + mil + dos_mil + cinco_mil + diez_mil + veinte_mil + cincuenta_mil + cien_mil);
        DecimalFormat df = new DecimalFormat("#,###");
        txtTotal.setText(df.format(total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        PanelContenedor1 = new rojeru_san.rspanel.RSPanelImage();
        btnFinalizar = new RSMaterialComponent.RSButtonIconUno();
        Separador1 = new javax.swing.JSeparator();
        LabelTitulo1 = new javax.swing.JLabel();
        rSButtonIconOne1 = new RSMaterialComponent.RSButtonIconOne();
        txtIDArreglo = new javax.swing.JTextField();
        txtEvento = new javax.swing.JTextField();
        txtIDCaj = new javax.swing.JTextField();
        txtIDBoca = new javax.swing.JTextField();
        cboConcepto = new RSMaterialComponent.RSComboBox();
        txt50 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt100 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt500 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt1000 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt2000 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt100000 = new javax.swing.JTextField();
        txt50000 = new javax.swing.JTextField();
        txt20000 = new javax.swing.JTextField();
        txt10000 = new javax.swing.JTextField();
        txt5000 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lbTotalValores = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelContenedor1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Recursos/CONTENEDOR2.png"))); // NOI18N

        btnFinalizar.setBackground(new java.awt.Color(255, 255, 255));
        btnFinalizar.setBackgroundHover(new java.awt.Color(0, 153, 153));
        btnFinalizar.setForegroundText(new java.awt.Color(0, 153, 153));
        btnFinalizar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CHECK);
        btnFinalizar.setRippleColor(java.awt.Color.white);
        btnFinalizar.setTypeBorder(RSMaterialComponent.RSButtonIconUno.TYPEBORDER.CIRCLE);
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        Separador1.setForeground(new java.awt.Color(204, 204, 204));

        LabelTitulo1.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        LabelTitulo1.setForeground(new java.awt.Color(0, 102, 102));
        LabelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitulo1.setText("FINALIZAR");

        javax.swing.GroupLayout PanelContenedor1Layout = new javax.swing.GroupLayout(PanelContenedor1);
        PanelContenedor1.setLayout(PanelContenedor1Layout);
        PanelContenedor1Layout.setHorizontalGroup(
            PanelContenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContenedor1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelContenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Separador1)
                    .addComponent(LabelTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PanelContenedor1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        PanelContenedor1Layout.setVerticalGroup(
            PanelContenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContenedor1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(Separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(LabelTitulo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(PanelContenedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        rSButtonIconOne1.setBackground(new java.awt.Color(0, 102, 102));
        rSButtonIconOne1.setBackgroundHover(new java.awt.Color(255, 0, 0));
        rSButtonIconOne1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        rSButtonIconOne1.setOpaque(true);
        rSButtonIconOne1.setPreferredSize(new java.awt.Dimension(15, 15));
        rSButtonIconOne1.setRequestFocusEnabled(false);
        rSButtonIconOne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconOne1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonIconOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 0, -1, -1));
        jPanel2.add(txtIDArreglo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 70, -1));
        jPanel2.add(txtEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 34, 44, -1));

        txtIDCaj.setEditable(false);
        txtIDCaj.setBackground(new java.awt.Color(255, 255, 255));
        txtIDCaj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.add(txtIDCaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 70, 23));

        txtIDBoca.setEditable(false);
        txtIDBoca.setBackground(new java.awt.Color(255, 255, 255));
        txtIDBoca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.add(txtIDBoca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 70, 23));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 250, -1));

        cboConcepto.setForeground(new java.awt.Color(0, 0, 0));
        cboConcepto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EN CONCEPTO DE:", "RETIRO", "CIERRE", "GASTO" }));
        cboConcepto.setColorArrow(new java.awt.Color(255, 255, 255));
        cboConcepto.setColorBorde(new java.awt.Color(204, 204, 204));
        cboConcepto.setColorBoton(new java.awt.Color(153, 153, 153));
        cboConcepto.setColorFondo(new java.awt.Color(255, 255, 255));
        cboConcepto.setColorSeleccion(new java.awt.Color(0, 102, 102));
        cboConcepto.setConBorde(true);
        cboConcepto.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cboConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboConceptoActionPerformed(evt);
            }
        });
        cboConcepto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboConceptoKeyPressed(evt);
            }
        });
        jPanel1.add(cboConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, 23));

        txt50.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt50.setText("0");
        txt50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt50ActionPerformed(evt);
            }
        });
        txt50.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt50KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt50KeyReleased(evt);
            }
        });
        jPanel1.add(txt50, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 60, 23));

        jLabel5.setText("50");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 23));

        jLabel6.setText("100");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 23));

        txt100.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt100.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt100.setText("0");
        txt100.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt100ActionPerformed(evt);
            }
        });
        txt100.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt100KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt100KeyReleased(evt);
            }
        });
        jPanel1.add(txt100, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 60, 23));

        jLabel7.setText("500");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 23));

        txt500.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt500.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt500.setText("0");
        txt500.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt500ActionPerformed(evt);
            }
        });
        txt500.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt500KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt500KeyReleased(evt);
            }
        });
        jPanel1.add(txt500, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 60, 23));

        jLabel8.setText("1.000");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 23));

        txt1000.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt1000.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt1000.setText("0");
        txt1000.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1000ActionPerformed(evt);
            }
        });
        txt1000.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt1000KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt1000KeyReleased(evt);
            }
        });
        jPanel1.add(txt1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 60, 23));

        jLabel9.setText("2.000");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 23));

        txt2000.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt2000.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt2000.setText("0");
        txt2000.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt2000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2000ActionPerformed(evt);
            }
        });
        txt2000.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt2000KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt2000KeyReleased(evt);
            }
        });
        jPanel1.add(txt2000, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 60, 23));

        jLabel10.setText("5.000");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, 23));

        jLabel11.setText("10.000");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, 23));

        jLabel12.setText("20.000");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, 23));

        jLabel13.setText("50.000");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, 23));

        jLabel14.setText("100.000");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, 23));

        txt100000.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt100000.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt100000.setText("0");
        txt100000.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt100000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt100000ActionPerformed(evt);
            }
        });
        txt100000.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt100000KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt100000KeyReleased(evt);
            }
        });
        jPanel1.add(txt100000, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 60, 23));

        txt50000.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt50000.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt50000.setText("0");
        txt50000.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt50000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt50000ActionPerformed(evt);
            }
        });
        txt50000.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt50000KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt50000KeyReleased(evt);
            }
        });
        jPanel1.add(txt50000, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 60, 23));

        txt20000.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt20000.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt20000.setText("0");
        txt20000.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt20000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt20000ActionPerformed(evt);
            }
        });
        txt20000.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt20000KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt20000KeyReleased(evt);
            }
        });
        jPanel1.add(txt20000, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 60, 23));

        txt10000.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt10000.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt10000.setText("0");
        txt10000.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt10000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt10000ActionPerformed(evt);
            }
        });
        txt10000.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt10000KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt10000KeyReleased(evt);
            }
        });
        jPanel1.add(txt10000, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 60, 23));

        txt5000.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt5000.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt5000.setText("0");
        txt5000.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt5000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt5000ActionPerformed(evt);
            }
        });
        txt5000.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt5000KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt5000KeyReleased(evt);
            }
        });
        jPanel1.add(txt5000, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 60, 23));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 230, 10));

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 230, 10));

        lbTotalValores.setText("TOTAL DE VALORES");
        jPanel1.add(lbTotalValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 115, 23));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtTotal.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(0, 102, 102));
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.setText("0");
        txtTotal.setToolTipText("");
        txtTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalKeyReleased(evt);
            }
        });
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 110, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        //int resp = JOptionPane.showConfirmDialog(this, "¿Desea guardar información de valores?", "BOCA DE COBRANZA 1", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (cboConcepto.getSelectedIndex() == 0) {
            Mensajes.Sistema("Seleccione el Concepto del arreglo");
            cboConcepto.requestFocus();
            cboConcepto.setPopupVisible(true);
        } else if (Integer.parseInt(txtTotal.getText().replace(".", "").replace(",", "")) <= 0) {
            Mensajes.Sistema("No ha detallado la cantidad de los valores.");
            switch (cboConcepto.getSelectedIndex()) {
                case 1 -> {
                    txt50.requestFocus();
                    txt50.selectAll();
                }
                case 2 -> {
                    txt50.requestFocus();
                    txt50.selectAll();
                }
                case 3 -> {
                    txtTotal.requestFocus();
                    txtTotal.selectAll();
                }
                default -> {
                }
            }

        } else {
            if (txtEvento.getText().equals("N")) {
                int resp = Mensajes.confirmar("¿Seguro que desea guardar la información de valores?");
                if (resp == JOptionPane.YES_OPTION) {
                    ControlCaja.addArreglo();
                    this.dispose();
                }
            } else if (txtEvento.getText().equals("M")) {
                int resp = Mensajes.confirmar("¿Seguro que desea modificar la información de valores?");
                if (resp == JOptionPane.YES_OPTION) {
                    ControlCaja.actArreglo();
                    this.dispose();
                }
            }

        }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void cboConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboConceptoActionPerformed
        // TODO add your handling code here:
        switch (cboConcepto.getSelectedIndex()) {
            case 0 -> {
                Habilitar(false);
                txtTotal.setEditable(false);
                txtTotal.setText("0");
                btnFinalizar.setEnabled(true);
            }
            case 1 -> {
                String cierre = generarCodigos.ObtenerCodigo2("SELECT concepto FROM arreglo_caja_2 WHERE idcaja=" + dlgRegistroValores.txtCaja.getText() + " AND idboca=" + Timbrado.getIdBoca() + " AND concepto='C' AND estado='S'");
                System.out.println("Cierre: " + cierre);
                if (cierre == null) {
                    Habilitar(true);
                    txtTotal.setEditable(false);
                    txt50.requestFocus();
                    Calculadora();
                    btnFinalizar.setEnabled(true);
                } else {
                    Mensajes.Alerta("Esta boca de cobranza ya registro el cierre de valores.");
                    Habilitar(false);
                    txtTotal.setEditable(false);
                    btnFinalizar.setEnabled(false);
                }

            }
            case 2 -> {
                String cierre = generarCodigos.ObtenerCodigo2("SELECT concepto FROM arreglo_caja_2 WHERE idcaja=" + dlgRegistroValores.txtCaja.getText() + " AND idboca=" + Timbrado.getIdBoca() + " AND concepto='C' AND estado='S'");
                System.out.println("Cierre: " + cierre);
                if (cierre == null) {
                    if (txtEvento.getText().equals("N")) {
                        Mensajes.Alerta("¡Observación importante!\r\nAl registrar el CIERRE DE VALORES ya no podra efectuar ventas en esta caja.\r\nFavor tener en cuenta esta información");
                        btnFinalizar.setEnabled(true);
                    }
                    Habilitar(true);
                    txtTotal.setEditable(false);
                    txt50.requestFocus();
                    Calculadora();
                } else {
                    Mensajes.Alerta("Esta boca de cobranza ya registro el cierre de valores.");
                    Habilitar(false);
                    txtTotal.setEditable(false);
                    btnFinalizar.setEnabled(false);
                }

            }
            case 3 -> {
                String cierre = generarCodigos.ObtenerCodigo2("SELECT concepto FROM arreglo_caja_2 WHERE idcaja=" + dlgRegistroValores.txtCaja.getText() + " AND idboca=" + Timbrado.getIdBoca() + " AND concepto='C' AND estado='S'");
                System.out.println("Cierre: " + cierre);
                if (cierre == null) {
                    Habilitar(false);
                    txtTotal.setEditable(true);
                    txtTotal.requestFocus();
                    txtTotal.setText("0");
                    btnFinalizar.setEnabled(true);
                } else {
                    Mensajes.Alerta("Esta boca de cobranza ya registro el cierre de valores.");
                    Habilitar(false);
                    txtTotal.setEditable(false);
                    btnFinalizar.setEnabled(false);
                }

            }
            default -> {
            }
        }

    }//GEN-LAST:event_cboConceptoActionPerformed

    private void cboConceptoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboConceptoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboConceptoKeyPressed

    private void txt50KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt50KeyPressed
        // TODO add your handling code here:
        if (!txt50.getText().trim().isEmpty()) {
            validarCampos.soloNumeros(txt50);
        }
    }//GEN-LAST:event_txt50KeyPressed

    private void txt100KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt100KeyPressed
        // TODO add your handling code here:
        if (!txt100.getText().trim().isEmpty()) {
            validarCampos.soloNumeros(txt100);
        }
    }//GEN-LAST:event_txt100KeyPressed

    private void txt500KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt500KeyPressed
        // TODO add your handling code here:
        if (!txt500.getText().trim().isEmpty()) {
            validarCampos.soloNumeros(txt500);
        }
    }//GEN-LAST:event_txt500KeyPressed

    private void txt1000KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1000KeyPressed
        // TODO add your handling code here:
        if (!txt1000.getText().trim().isEmpty()) {
            validarCampos.soloNumeros(txt1000);
        }
    }//GEN-LAST:event_txt1000KeyPressed

    private void txt2000KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt2000KeyPressed
        // TODO add your handling code here:
        if (!txt2000.getText().trim().isEmpty()) {
            validarCampos.soloNumeros(txt2000);
        }
    }//GEN-LAST:event_txt2000KeyPressed

    private void txt5000KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt5000KeyPressed
        // TODO add your handling code here:
        if (!txt5000.getText().trim().isEmpty()) {
            validarCampos.soloNumeros(txt5000);
        }
    }//GEN-LAST:event_txt5000KeyPressed

    private void txt10000KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt10000KeyPressed
        // TODO add your handling code here:
        if (!txt10000.getText().trim().isEmpty()) {
            validarCampos.soloNumeros(txt10000);
        }
    }//GEN-LAST:event_txt10000KeyPressed

    private void txt20000KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt20000KeyPressed
        // TODO add your handling code here:
        if (!txt20000.getText().trim().isEmpty()) {
            validarCampos.soloNumeros(txt20000);
        }
    }//GEN-LAST:event_txt20000KeyPressed

    private void txt50000KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt50000KeyPressed
        // TODO add your handling code here:
        if (!txt50000.getText().trim().isEmpty()) {
            validarCampos.soloNumeros(txt50000);
        }
    }//GEN-LAST:event_txt50000KeyPressed

    private void txt100000KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt100000KeyPressed
        // TODO add your handling code here:
        if (!txt100000.getText().trim().isEmpty()) {
            validarCampos.soloNumeros(txt100000);
        }
    }//GEN-LAST:event_txt100000KeyPressed

    private void txt50KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt50KeyReleased
        // TODO add your handling code here:
        try {
            if (txt50.getText().trim().length() >= 1) {
                DecimalFormat df = new DecimalFormat("#,###");
                txt50.setText(df.format(Integer.valueOf(txt50.getText().trim().replace(".", "").replace(",", ""))));
            } else {
                txt50.setText("0");
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        }
        Calculadora();
    }//GEN-LAST:event_txt50KeyReleased

    private void txt100KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt100KeyReleased
        // TODO add your handling code here:
        try {
            if (txt100.getText().trim().length() >= 1) {
                DecimalFormat df = new DecimalFormat("#,###");
                txt100.setText(df.format(Integer.valueOf(txt100.getText().trim().replace(".", "").replace(",", ""))));
            } else {
                txt100.setText("0");
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        }
        Calculadora();
    }//GEN-LAST:event_txt100KeyReleased

    private void txt500KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt500KeyReleased
        // TODO add your handling code here:
        try {
            if (txt500.getText().trim().length() >= 1) {
                DecimalFormat df = new DecimalFormat("#,###");
                txt500.setText(df.format(Integer.valueOf(txt500.getText().trim().replace(".", "").replace(",", ""))));
            } else {
                txt500.setText("0");
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        }
        Calculadora();
    }//GEN-LAST:event_txt500KeyReleased

    private void txt1000KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1000KeyReleased
        // TODO add your handling code here:
        try {
            if (txt1000.getText().trim().length() >= 1) {
                DecimalFormat df = new DecimalFormat("#,###");
                txt1000.setText(df.format(Integer.valueOf(txt1000.getText().trim().replace(".", "").replace(",", ""))));
            } else {
                txt1000.setText("0");
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        }
        Calculadora();
    }//GEN-LAST:event_txt1000KeyReleased

    private void txt2000KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt2000KeyReleased
        // TODO add your handling code here:
        try {
            if (txt2000.getText().trim().length() >= 1) {
                DecimalFormat df = new DecimalFormat("#,###");
                txt2000.setText(df.format(Integer.valueOf(txt2000.getText().trim().replace(".", "").replace(",", ""))));
            } else {
                txt2000.setText("0");
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        }
        Calculadora();
    }//GEN-LAST:event_txt2000KeyReleased

    private void txt5000KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt5000KeyReleased
        // TODO add your handling code here:
        try {
            if (txt5000.getText().trim().length() >= 1) {
                DecimalFormat df = new DecimalFormat("#,###");
                txt5000.setText(df.format(Integer.valueOf(txt5000.getText().trim().replace(".", "").replace(",", ""))));
            } else {
                txt5000.setText("0");
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        }
        Calculadora();
    }//GEN-LAST:event_txt5000KeyReleased

    private void txt10000KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt10000KeyReleased
        // TODO add your handling code here:
        try {
            if (txt10000.getText().trim().length() >= 1) {
                DecimalFormat df = new DecimalFormat("#,###");
                txt10000.setText(df.format(Integer.valueOf(txt10000.getText().trim().replace(".", "").replace(",", ""))));
            } else {
                txt10000.setText("0");
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        }
        Calculadora();
    }//GEN-LAST:event_txt10000KeyReleased

    private void txt20000KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt20000KeyReleased
        // TODO add your handling code here:
        try {
            if (txt20000.getText().trim().length() >= 1) {
                DecimalFormat df = new DecimalFormat("#,###");
                txt20000.setText(df.format(Integer.valueOf(txt20000.getText().trim().replace(".", "").replace(",", ""))));
            } else {
                txt20000.setText("0");
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        }
        Calculadora();
    }//GEN-LAST:event_txt20000KeyReleased

    private void txt50000KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt50000KeyReleased
        // TODO add your handling code here:
        try {
            if (txt50000.getText().trim().length() >= 1) {
                DecimalFormat df = new DecimalFormat("#,###");
                txt50000.setText(df.format(Integer.valueOf(txt50000.getText().trim().replace(".", "").replace(",", ""))));
            } else {
                txt50000.setText("0");
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        }
        Calculadora();
    }//GEN-LAST:event_txt50000KeyReleased

    private void txt100000KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt100000KeyReleased
        // TODO add your handling code here:
        try {
            if (txt100000.getText().trim().length() >= 1) {
                DecimalFormat df = new DecimalFormat("#,###");
                txt100000.setText(df.format(Integer.valueOf(txt100000.getText().trim().replace(".", "").replace(",", ""))));
            } else {
                txt100000.setText("0");
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        }
        Calculadora();
    }//GEN-LAST:event_txt100000KeyReleased

    private void rSButtonIconOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconOne1ActionPerformed
        // TODO add your handling code here:
        int rpta = Mensajes.confirmar("¿Seguro que desea salir del formulario?");
        if (rpta == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_rSButtonIconOne1ActionPerformed

    private void txt50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt50ActionPerformed
        // TODO add your handling code here:
        txt100.requestFocus();
        txt100.selectAll();
    }//GEN-LAST:event_txt50ActionPerformed

    private void txt100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt100ActionPerformed
        // TODO add your handling code here:
        txt500.requestFocus();
        txt500.selectAll();
    }//GEN-LAST:event_txt100ActionPerformed

    private void txt500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt500ActionPerformed
        // TODO add your handling code here:
        txt1000.requestFocus();
        txt1000.selectAll();
    }//GEN-LAST:event_txt500ActionPerformed

    private void txt1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1000ActionPerformed
        // TODO add your handling code here:
        txt2000.requestFocus();
        txt2000.selectAll();
    }//GEN-LAST:event_txt1000ActionPerformed

    private void txt2000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2000ActionPerformed
        // TODO add your handling code here:
        txt5000.requestFocus();
        txt5000.selectAll();
    }//GEN-LAST:event_txt2000ActionPerformed

    private void txt5000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt5000ActionPerformed
        // TODO add your handling code here:
        txt10000.requestFocus();
        txt10000.selectAll();
    }//GEN-LAST:event_txt5000ActionPerformed

    private void txt10000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt10000ActionPerformed
        // TODO add your handling code here:
        txt20000.requestFocus();
        txt20000.selectAll();
    }//GEN-LAST:event_txt10000ActionPerformed

    private void txt20000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt20000ActionPerformed
        // TODO add your handling code here:
        txt50000.requestFocus();
        txt50000.selectAll();
    }//GEN-LAST:event_txt20000ActionPerformed

    private void txt50000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt50000ActionPerformed
        // TODO add your handling code here:
        txt100000.requestFocus();
        txt100000.selectAll();
    }//GEN-LAST:event_txt50000ActionPerformed

    private void txt100000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt100000ActionPerformed
        // TODO add your handling code here:
        btnFinalizar.doClick();
    }//GEN-LAST:event_txt100000ActionPerformed

    private void txtTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyReleased
        // TODO add your handling code here:
        try {
            if (txtTotal.getText().trim().length() >= 1) {
                DecimalFormat df = new DecimalFormat("#,###");
                txtTotal.setText(df.format(Integer.valueOf(txtTotal.getText().trim().replace(".", "").replace(",", ""))));
            } else {
                txtTotal.setText("0");
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_txtTotalKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgArreglo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgArreglo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgArreglo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgArreglo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgArreglo dialog = new dlgArreglo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTitulo1;
    private rojeru_san.rspanel.RSPanelImage PanelContenedor1;
    private javax.swing.JSeparator Separador1;
    private RSMaterialComponent.RSButtonIconUno btnFinalizar;
    public static RSMaterialComponent.RSComboBox cboConcepto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbTotalValores;
    private RSMaterialComponent.RSButtonIconOne rSButtonIconOne1;
    public static javax.swing.JTextField txt100;
    public static javax.swing.JTextField txt1000;
    public static javax.swing.JTextField txt10000;
    public static javax.swing.JTextField txt100000;
    public static javax.swing.JTextField txt2000;
    public static javax.swing.JTextField txt20000;
    public static javax.swing.JTextField txt50;
    public static javax.swing.JTextField txt500;
    public static javax.swing.JTextField txt5000;
    public static javax.swing.JTextField txt50000;
    public static javax.swing.JTextField txtEvento;
    public static javax.swing.JTextField txtIDArreglo;
    public static javax.swing.JTextField txtIDBoca;
    public static javax.swing.JTextField txtIDCaj;
    public static javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
