/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IU;

import Componentes.Login;
import Componentes.Mensajes;
import Controladores.controlUsuario;
import java.awt.HeadlessException;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class dlgActualizarContra extends javax.swing.JDialog {

    /**
     * Creates new form dlgActualizarContra
     *
     * @param parent
     * @param modal
     */
    char i;
    char ii;
    char iii;

    public dlgActualizarContra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lbID.setVisible(false);
        lbID.setText(Login.getIDUsuarioLogueado());
        txtUsuario.setText(Login.getUsuarioLogueado());
        txtContra.requestFocus();
        i = txtContra.getEchoChar();
        ii = txtContraN.getEchoChar();
        iii = txtContraC.getEchoChar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsuario = new RSMaterialComponent.RSTextFieldMaterialIcon();
        txtContra = new RSMaterialComponent.RSPasswordMaterialIcon();
        btnActivarCA = new javax.swing.JToggleButton();
        txtContraN = new RSMaterialComponent.RSPasswordMaterialIcon();
        txtContraC = new RSMaterialComponent.RSPasswordMaterialIcon();
        btnActivaNC = new javax.swing.JToggleButton();
        btnActivarCC = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnModificar = new newscomponents.RSButtonBigIcon_new();
        btnCancelar = new newscomponents.RSButtonBigIcon_new();
        btnSalir1 = new newscomponents.RSButtonBigIcon_new();
        lbID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setText("USUARIO ACTUAL");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel2.setText("CONTRASEÑA ACTUAL");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setText("NUEVA CONTRASEÑA");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setText("CONFIRMAR CONTRASEÑA");

        txtUsuario.setEditable(false);
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuario.setColorIcon(new java.awt.Color(0, 102, 102));
        txtUsuario.setColorMaterial(new java.awt.Color(0, 102, 102));
        txtUsuario.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        txtUsuario.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);
        txtUsuario.setPhColor(new java.awt.Color(17, 35, 46));
        txtUsuario.setPlaceholder("");
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtContra.setForeground(new java.awt.Color(0, 0, 0));
        txtContra.setColorIcon(new java.awt.Color(0, 102, 102));
        txtContra.setColorMaterial(new java.awt.Color(0, 102, 102));
        txtContra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtContra.setPhColor(new java.awt.Color(17, 35, 46));
        txtContra.setPlaceholder("");
        txtContra.setSelectionColor(new java.awt.Color(17, 35, 46));
        txtContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraActionPerformed(evt);
            }
        });

        btnActivarCA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/baseline_visibility_black_20.png"))); // NOI18N
        btnActivarCA.setBorder(null);
        btnActivarCA.setBorderPainted(false);
        btnActivarCA.setFocusPainted(false);
        btnActivarCA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnActivarCAItemStateChanged(evt);
            }
        });
        btnActivarCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarCAActionPerformed(evt);
            }
        });

        txtContraN.setEditable(false);
        txtContraN.setForeground(new java.awt.Color(0, 0, 0));
        txtContraN.setColorIcon(new java.awt.Color(0, 102, 102));
        txtContraN.setColorMaterial(new java.awt.Color(0, 102, 102));
        txtContraN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtContraN.setPhColor(new java.awt.Color(17, 35, 46));
        txtContraN.setPlaceholder("");
        txtContraN.setSelectionColor(new java.awt.Color(17, 35, 46));
        txtContraN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraNKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContraNKeyTyped(evt);
            }
        });

        txtContraC.setEditable(false);
        txtContraC.setForeground(new java.awt.Color(0, 0, 0));
        txtContraC.setColorIcon(new java.awt.Color(0, 102, 102));
        txtContraC.setColorMaterial(new java.awt.Color(0, 102, 102));
        txtContraC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtContraC.setPhColor(new java.awt.Color(17, 35, 46));
        txtContraC.setPlaceholder("");
        txtContraC.setSelectionColor(new java.awt.Color(17, 35, 46));
        txtContraC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraCKeyPressed(evt);
            }
        });

        btnActivaNC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/baseline_visibility_black_20.png"))); // NOI18N
        btnActivaNC.setBorder(null);
        btnActivaNC.setBorderPainted(false);
        btnActivaNC.setEnabled(false);
        btnActivaNC.setFocusPainted(false);
        btnActivaNC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnActivaNCItemStateChanged(evt);
            }
        });
        btnActivaNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivaNCActionPerformed(evt);
            }
        });

        btnActivarCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/baseline_visibility_black_20.png"))); // NOI18N
        btnActivarCC.setBorder(null);
        btnActivarCC.setBorderPainted(false);
        btnActivarCC.setEnabled(false);
        btnActivarCC.setFocusPainted(false);
        btnActivarCC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnActivarCCItemStateChanged(evt);
            }
        });
        btnActivarCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarCCActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btnModificar.setBackground(new java.awt.Color(0, 102, 102));
        btnModificar.setBorder(null);
        btnModificar.setText("MODIFICAR");
        btnModificar.setBgHover(new java.awt.Color(0, 153, 153));
        btnModificar.setFocusPainted(false);
        btnModificar.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnModificar.setIconTextGap(0);
        btnModificar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnModificar.setPixels(0);
        btnModificar.setSizeIcon(50.0F);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar);

        btnCancelar.setBackground(new java.awt.Color(0, 102, 102));
        btnCancelar.setBorder(null);
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBgHover(new java.awt.Color(0, 153, 153));
        btnCancelar.setFocusPainted(false);
        btnCancelar.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnCancelar.setIconTextGap(0);
        btnCancelar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        btnCancelar.setPixels(0);
        btnCancelar.setSizeIcon(50.0F);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);

        btnSalir1.setBackground(new java.awt.Color(0, 102, 102));
        btnSalir1.setBorder(null);
        btnSalir1.setBgHover(new java.awt.Color(255, 0, 0));
        btnSalir1.setFocusPainted(false);
        btnSalir1.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnSalir1.setIconTextGap(0);
        btnSalir1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnSalir1.setPixels(0);
        btnSalir1.setSizeIcon(15.0F);
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        lbID.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContraN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContraC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnActivarCA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActivaNC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActivarCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnActivarCA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContraN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(btnActivaNC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtContraC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(btnActivarCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if (String.valueOf(txtContraN.getPassword()).isEmpty()) {
            txtContraN.requestFocus();
        } else if (String.valueOf(txtContraC.getPassword()).isEmpty()) {
            txtContraC.requestFocus();
        } else if (!String.valueOf(txtContraN.getPassword()).equals(String.valueOf(txtContraC.getPassword()))) {
            Mensajes.error("La nueva contraseña no paso la validación de coincidencia.");
        } else {
            try {
                int resp = JOptionPane.showConfirmDialog(this, "¿Seguro que desea modificar su contraseña de acceso?", "Modificar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (resp == JOptionPane.YES_OPTION) {
                    controlUsuario.actPassword();
                    btnCancelarActionPerformed(null);
                }
            } catch (HeadlessException ee) {
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        txtUsuario.setText("");
        txtContra.setText("");
        txtContraN.setText("");
        txtContraC.setText("");
        lbID.setText("");
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        // TODO add your handling code here:
        int rpta = Mensajes.confirmar("¿Seguro que desea salir del formulario?");
        if (rpta == 0) {
            this.dispose();
        } else {
            txtContra.requestFocus();
        }
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnActivarCAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnActivarCAItemStateChanged
        // TODO add your handling code here:
        int estado = evt.getStateChange();
        if (estado == ItemEvent.SELECTED) {
            txtContra.setEchoChar((char) 0);
            btnActivarCA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/baseline_visibility_off_black_20.png")));
            txtContra.setFont(new java.awt.Font("Roboto", 1, 12));
        } else {
            txtContra.setEchoChar(i);
            btnActivarCA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/baseline_visibility_black_20.png")));
            txtContra.setFont(new java.awt.Font("Tahoma", 1, 12));
        }
    }//GEN-LAST:event_btnActivarCAItemStateChanged

    private void btnActivarCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActivarCAActionPerformed

    private void btnActivaNCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnActivaNCItemStateChanged
        // TODO add your handling code here:
        int estado = evt.getStateChange();
        if (estado == ItemEvent.SELECTED) {
            txtContraN.setEchoChar((char) 0);
            btnActivaNC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/baseline_visibility_off_black_20.png")));
            txtContraN.setFont(new java.awt.Font("Roboto", 1, 12));
        } else {
            txtContraN.setEchoChar(ii);
            btnActivaNC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/baseline_visibility_black_20.png")));
            txtContraN.setFont(new java.awt.Font("Tahoma", 1, 12));
        }
    }//GEN-LAST:event_btnActivaNCItemStateChanged

    private void btnActivaNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivaNCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActivaNCActionPerformed

    private void btnActivarCCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnActivarCCItemStateChanged
        // TODO add your handling code here:
        int estado = evt.getStateChange();
        if (estado == ItemEvent.SELECTED) {
            txtContraC.setEchoChar((char) 0);
            btnActivarCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/baseline_visibility_off_black_20.png")));
            txtContraC.setFont(new java.awt.Font("Roboto", 1, 12));
        } else {
            txtContraC.setEchoChar(iii);
            btnActivarCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/baseline_visibility_black_20.png")));
            txtContraC.setFont(new java.awt.Font("Tahoma", 1, 12));
        }
    }//GEN-LAST:event_btnActivarCCItemStateChanged

    private void btnActivarCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActivarCCActionPerformed

    private void txtContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraActionPerformed
        // TODO add your handling code here:
        if (String.valueOf(txtContra.getPassword()).equals(Login.getContraLogueado())) {
            txtContraN.setEditable(true);
            btnActivaNC.setEnabled(true);
            txtContraC.setEditable(true);
            btnActivarCC.setEnabled(true);
            txtContra.setEditable(false);
            txtContraN.requestFocus();
        } else {
            Mensajes.error("La contrasena actual ingresado no es la correcta.");
        }
    }//GEN-LAST:event_txtContraActionPerformed

    private void txtContraNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraNKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraNKeyTyped

    private void txtContraNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraNKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtContraC.requestFocus();
        }
    }//GEN-LAST:event_txtContraNKeyPressed

    private void txtContraCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraCKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnModificar.doClick();
        }
    }//GEN-LAST:event_txtContraCKeyPressed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgActualizarContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgActualizarContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgActualizarContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgActualizarContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            dlgActualizarContra dialog = new dlgActualizarContra(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnActivaNC;
    private javax.swing.JToggleButton btnActivarCA;
    private javax.swing.JToggleButton btnActivarCC;
    public static newscomponents.RSButtonBigIcon_new btnCancelar;
    public static newscomponents.RSButtonBigIcon_new btnModificar;
    public static newscomponents.RSButtonBigIcon_new btnSalir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel lbID;
    private RSMaterialComponent.RSPasswordMaterialIcon txtContra;
    private RSMaterialComponent.RSPasswordMaterialIcon txtContraC;
    public static RSMaterialComponent.RSPasswordMaterialIcon txtContraN;
    private RSMaterialComponent.RSTextFieldMaterialIcon txtUsuario;
    // End of variables declaration//GEN-END:variables
}
