
package IU;

public class dlgTicketVenta extends javax.swing.JFrame {

    public dlgTicketVenta() {
        initComponents();
  }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ticket = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbTicket = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbCondicion = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFechaHora = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbCaja = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbCliente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetalle = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        lbVendedor1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbRecibido = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbRecibido1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbVendedor = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDetalle = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ticket.setBackground(new java.awt.Color(255, 255, 255));
        ticket.setLayout(null);

        jLabel1.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("R.U.C.: 4324377-0");
        ticket.add(jLabel1);
        jLabel1.setBounds(0, 40, 310, 16);

        jLabel6.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("FARMACIA FARMAMILI");
        ticket.add(jLabel6);
        jLabel6.setBounds(0, 15, 310, 25);

        jLabel2.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("de Alfonso Avalos Gimenez");
        ticket.add(jLabel2);
        jLabel2.setBounds(0, 60, 310, 16);

        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Jose M. A. Godoy c/ Las Residentas");
        ticket.add(jLabel3);
        jLabel3.setBounds(0, 80, 310, 16);

        jLabel4.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cel: (0981) 700 414 / (0971) 799 004");
        ticket.add(jLabel4);
        jLabel4.setBounds(0, 100, 310, 16);

        jLabel5.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cnel. Oviedo - Paraguay");
        ticket.add(jLabel5);
        jLabel5.setBounds(0, 120, 310, 20);

        jLabel7.setText(" ----------------------------------------------------------------------------");
        ticket.add(jLabel7);
        jLabel7.setBounds(0, 600, 310, 14);

        jLabel8.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jLabel8.setText("Ticket N°:");
        ticket.add(jLabel8);
        jLabel8.setBounds(10, 170, 70, 16);

        lbTicket.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        lbTicket.setText("ticket");
        ticket.add(lbTicket);
        lbTicket.setBounds(90, 170, 200, 16);

        jLabel10.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jLabel10.setText("Condición:");
        ticket.add(jLabel10);
        jLabel10.setBounds(10, 190, 70, 16);

        lbCondicion.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        lbCondicion.setText("C");
        ticket.add(lbCondicion);
        lbCondicion.setBounds(90, 190, 200, 16);

        jLabel12.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jLabel12.setText("Fecha:");
        ticket.add(jLabel12);
        jLabel12.setBounds(10, 210, 70, 16);

        txtFechaHora.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        txtFechaHora.setText("fecha+hora");
        ticket.add(txtFechaHora);
        txtFechaHora.setBounds(90, 210, 200, 16);

        jLabel13.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jLabel13.setText("Caja:");
        ticket.add(jLabel13);
        jLabel13.setBounds(10, 230, 70, 16);

        lbCaja.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        lbCaja.setText("caja");
        ticket.add(lbCaja);
        lbCaja.setBounds(90, 230, 200, 16);

        jLabel14.setFont(new java.awt.Font("DialogInput", 1, 11)); // NOI18N
        jLabel14.setText(" Cant.    P.Publico    P.c/Desc.   Monto");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        ticket.add(jLabel14);
        jLabel14.setBounds(10, 280, 290, 18);

        lbCliente.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        lbCliente.setText("Cliente");
        ticket.add(lbCliente);
        lbCliente.setBounds(90, 250, 200, 16);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtDetalle.setEditable(false);
        txtDetalle.setColumns(4);
        txtDetalle.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        txtDetalle.setRows(5);
        txtDetalle.setText("KITADOL FORTE COMP. X 10\n 1        4.400       3.000        3.000\nKITADOL FORTE COMP. X 10\n 1        4.400       3.000        3.000\nKITADOL FORTE COMP. X 10\n 1        4.400       3.000        3.000\nKITADOL FORTE COMP. X 10\n 1        4.400       3.000        3.000\nKITADOL FORTE COMP. X 10\n 1        4.400       3.000        3.000\nKITADOL FORTE COMP. X 10\n 1        4.400       3.000        3.000");
        txtDetalle.setAutoscrolls(false);
        txtDetalle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtDetalle.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(txtDetalle);

        ticket.add(jScrollPane1);
        jScrollPane1.setBounds(10, 300, 290, 210);

        jLabel9.setText(" ----------------------------------------------------------------------------");
        ticket.add(jLabel9);
        jLabel9.setBounds(0, 150, 310, 14);

        jLabel15.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jLabel15.setText("Cliente:");
        ticket.add(jLabel15);
        jLabel15.setBounds(10, 250, 70, 16);

        jLabel16.setFont(new java.awt.Font("DialogInput", 1, 13)); // NOI18N
        jLabel16.setText("TOTAL:");
        ticket.add(jLabel16);
        jLabel16.setBounds(10, 520, 70, 18);

        lbTotal.setFont(new java.awt.Font("DialogInput", 1, 13)); // NOI18N
        lbTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTotal.setText("total");
        ticket.add(lbTotal);
        lbTotal.setBounds(90, 520, 210, 18);

        lbVendedor1.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        ticket.add(lbVendedor1);
        lbVendedor1.setBounds(90, 540, 200, 0);

        jLabel11.setText(" ----------------------------------------------------------------------------");
        ticket.add(jLabel11);
        jLabel11.setBounds(0, 510, 310, 14);

        jLabel18.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jLabel18.setText("Recibido:");
        ticket.add(jLabel18);
        jLabel18.setBounds(10, 540, 70, 16);

        lbRecibido.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        lbRecibido.setText("Recibido");
        ticket.add(lbRecibido);
        lbRecibido.setBounds(90, 540, 200, 16);

        jLabel19.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jLabel19.setText("Vuelto:");
        ticket.add(jLabel19);
        jLabel19.setBounds(10, 560, 70, 16);

        lbRecibido1.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        lbRecibido1.setText("Vuelto");
        ticket.add(lbRecibido1);
        lbRecibido1.setBounds(90, 560, 200, 16);

        jLabel20.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("PASADA 48HS NO ACEPTAMOS DEVOLUCIONES");
        ticket.add(jLabel20);
        jLabel20.setBounds(0, 640, 310, 16);

        lbVendedor.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        lbVendedor.setText("Vendedor");
        ticket.add(lbVendedor);
        lbVendedor.setBounds(90, 580, 200, 16);

        jLabel21.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jLabel21.setText("Vendedor:");
        ticket.add(jLabel21);
        jLabel21.setBounds(10, 580, 70, 16);

        jLabel22.setFont(new java.awt.Font("DialogInput", 0, 11)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("GRACIAS POR SU PREFERENCIA");
        ticket.add(jLabel22);
        jLabel22.setBounds(0, 620, 310, 16);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        tbDetalle.setAutoCreateColumnsFromModel(false);
        tbDetalle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tbDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N.Comercial", "Cant.", "Prec. U.", "Monto"
            }
        ));
        tbDetalle.setAutoscrolls(false);
        tbDetalle.setShowHorizontalLines(false);
        tbDetalle.setShowVerticalLines(false);
        tbDetalle.getTableHeader().setResizingAllowed(false);
        tbDetalle.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbDetalle);

        ticket.add(jScrollPane2);
        jScrollPane2.setBounds(330, 160, 280, 140);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ticket, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ticket, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgTicketVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new dlgTicketVenta().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCaja;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbCondicion;
    private javax.swing.JLabel lbRecibido;
    private javax.swing.JLabel lbRecibido1;
    private javax.swing.JLabel lbTicket;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbVendedor;
    private javax.swing.JLabel lbVendedor1;
    public static javax.swing.JTable tbDetalle;
    private javax.swing.JPanel ticket;
    private javax.swing.JTextArea txtDetalle;
    private javax.swing.JLabel txtFechaHora;
    // End of variables declaration//GEN-END:variables
}
